GLOBAL:
  loss: cross_entropy
  lrate: .1
  wreg: 0.001
  wrt: L2

LAYERS: 
  input: 50
  hidden_layers:
    - size: 80
      act: sigmoid
      wr: glorot
      # lrate: 0.02
    - size: 70
      act: relu
      wr: glorot
      # lrate: 0.01
    - size: 100
      act: sigmoid
      wr: glorot
      # lrate: 0.02
    - size: 30
      act: tanh
      wr: glorot
      # lrate: 0.01
    - size: 9
      act: relu
      wr: glorot
      br: (0 1)
  type: softmax

DATASET: 
  load: True
  name: 'dataset_2024-02-13_750_9_50'