GLOBAL:
  loss: cross_entropy
  lrate: .1  
  wreg: 0.0005
  wrt: L2

LAYERS: 
  input: 30
  hidden_layers:
    - size: 300
      act: relu
      wr: glorot
    - size: 400
      act: sigmoid
      wr: (-0.01 0.01)
      lrate: 0.02
    - size: 40
      act: sigmoid
      wr: glorot
    - size: 9
      act: relu
      wr: glorot
      br: (0 1)
  type: softmax

DATASET: 
  load: True
  name: 'dataset_2024-02-13_1500_9_30'