GLOBAL:
  loss: cross_entropy
  lrate: 1
  wreg: 0.1
  wrt: L2

LAYERS: 
  input: 20
  hidden_layers:
    - size: 20
      act: sigmoid
      # wr: (-0.1 0.1)
      lrate: 1
    - size: 5
      act: sigmoid
      # wr: glorot
      br: (0 1)
  type: softmax