GLOBAL:
  loss: cross_entropy
  lrate: .01
  wreg: 0.0001
  wrt: None

LAYERS: 
  input: 20
  hidden_layers:
    - size: 500
      act: relu
      wr: glorot
      # lrate: 0.02
    - size: 300
      act: relu
      wr: glorot
      # lrate: 0.01
    - size: 400
      act: relu
      wr: glorot
      lrate: 0.02
    - size: 100
      act: sigmoid
      wr: glorot
      # lrate: 0.01
    - size: 40
      act: relu
      wr: glorot
      # lrate: 0.01
    - size: 5
      act: relu
      wr: glorot
      br: (0 1)
  type: softmax

DATASET: 
  load: True
  name: 'dataset_2024-02-13_750_5_20'